services:
  dev-db:
    image: postgres:15
    container_name: dev_db_container
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root # This password will be used for the postgres user
      POSTGRES_DB: nest      # This database will be created, owned by POSTGRES_USER
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: # Defines the named volume